# prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # 'booknet-api' is the container_name from the API compose file
      - targets: ['booknet-api:8080']
        labels:
          application: 'booknet-api'
